services:
  postgres:
    image: postgres:15-alpine
    container_name: influencer-platform-postgres
    environment:
      POSTGRES_DB: influencer_platform_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdev123
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d influencer_platform_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local