ALTER TABLE "user_profiles" ALTER COLUMN "current_plan" SET DATA TYPE varchar(50);
ALTER TABLE "user_profiles" ALTER COLUMN "current_plan" SET DEFAULT 'free';
ALTER TABLE "user_profiles" ADD COLUMN "payment_method_id" text;
ALTER TABLE "user_profiles" ADD COLUMN "card_last_4" varchar(4);
ALTER TABLE "user_profiles" ADD COLUMN "card_brand" varchar(20);
ALTER TABLE "user_profiles" ADD COLUMN "card_exp_month" integer;
ALTER TABLE "user_profiles" ADD COLUMN "card_exp_year" integer;
ALTER TABLE "user_profiles" ADD COLUMN "billing_address_city" text;
ALTER TABLE "user_profiles" ADD COLUMN "billing_address_country" varchar(2);
ALTER TABLE "user_profiles" ADD COLUMN "billing_address_postal_code" varchar(20);
ALTER TABLE "user_profiles" ADD COLUMN "plan_campaigns_limit" integer;
ALTER TABLE "user_profiles" ADD COLUMN "plan_creators_limit" integer;
ALTER TABLE "user_profiles" ADD COLUMN "plan_features" jsonb;
ALTER TABLE "user_profiles" ADD COLUMN "usage_campaigns_current" integer DEFAULT 0;
ALTER TABLE "user_profiles" ADD COLUMN "usage_creators_current_month" integer DEFAULT 0;
ALTER TABLE "user_profiles" ADD COLUMN "usage_reset_date" timestamp DEFAULT now();
ALTER TABLE "user_profiles" ADD COLUMN "last_webhook_event" varchar(100);
ALTER TABLE "user_profiles" ADD COLUMN "last_webhook_timestamp" timestamp;
ALTER TABLE "user_profiles" ADD COLUMN "billing_sync_status" varchar(20) DEFAULT 'pending';
ALTER TABLE "user_profiles" ADD COLUMN "trial_conversion_date" timestamp;
ALTER TABLE "user_profiles" ADD COLUMN "subscription_cancel_date" timestamp;
ALTER TABLE "user_profiles" ADD COLUMN "subscription_renewal_date" timestamp;